version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: yii2-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret

  backend:
    build: backend
    container_name: yii2-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "21080:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      YII_ENV: dev

  frontend:
    build: frontend
    container_name: yii2-frontend
    restart: always
    depends_on:
      - mysql
    ports:
      - "20080:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      YII_ENV: dev

volumes:
  mysql_data:
